lzc-sdk-version: "0.1"
name: fuclaude
package: ghost.lzcapp.fuclaude
version: 0.0.1
description: ""
homepage: ""
author: ""
application:
  subdomain: fuclaude
  background_task: false
  multi_instance: false
  gpu_accel: false
  routes:
    - /=http://fuclaude.ghost.lzcapp.fuclaude.lzcapp:8181/
services:
  fuclaude:
    image: pengzhile/fuclaude
    environment:
      - TZ=Asia/Shanghai
      - FUCLAUDE_BIND=0.0.0.0:8181
      - FUCLAUDE_TIMEOUT=600
      - FUCLAUDE_PROXY_URL=
      - FUCLAUDE_REAL_LOGOUT=false
      - FUCLAUDE_SITE_PASSWORD=
      - FUCLAUDE_COOKIE_SECRET=1234567890abcdefghijklmnopqrstuv
      - FUCLAUDE_OPENAI_BASE_URL=https://api.openai.com/v1
      - FUCLAUDE_OPENAI_API_KEY=sk-xxx
      - FUCLAUDE_MODERATION_ENABLED=false
      - FUCLAUDE_SIGNUP_ENABLED=false
      - FUCLAUDE_SHOW_SESSION_KEY=false
